'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
export interface MatchingHeaderParticipant { ref: string; displayName: string; online: boolean }
export interface MatchingHeaderProps { sessionId:string; sessionName:string; sessionStatus:string; minGroupSize:number; maxGroupSize:number; deadlineAt:string|null; viewer:{displayName:string;role:'active'|'observer'}; participants:MatchingHeaderParticipant[]; isAdmin:boolean; isImpersonating:boolean }
export default function MatchingHeader(p: MatchingHeaderProps) {
 const router=useRouter(), [open,setOpen]=useState(false), [leaving,setLeaving]=useState(false), [error,setError]=useState<string|null>(null)
 const days=p.deadlineAt?Math.ceil((new Date(p.deadlineAt).getTime()-Date.now())/86400000):null
 async function leave(){if(!window.confirm('Покинуть сессию?'))return;setLeaving(true);setError(null);try{const r=await fetch(`/api/matching/sessions/${p.sessionId}/leave`,{method:'DELETE'});if(!r.ok){const b=await r.json().catch(()=>({})) as {error?:string};throw new Error(b.error??'Не удалось покинуть сессию')}router.push('/matching')}catch(e){setError(e instanceof Error?e.message:'Не удалось покинуть сессию')}finally{setLeaving(false)}}
 const groups=p.minGroupSize===p.maxGroupSize?`Группы по ${p.minGroupSize}`:`Группы ${p.minGroupSize}–${p.maxGroupSize}`
 return <>{p.isImpersonating&&<div data-testid="admin-impersonation-banner" style={{padding:'0.45rem 1.3rem',borderBottom:'1px solid var(--hair)',color:'var(--status-warn)'}}>👁 Просмотр за {p.viewer.displayName}<a href="/matching" style={{float:'right',color:'inherit'}}>← выйти из админ-режима</a></div>}<header data-testid="matching-header" style={{padding:'0.7rem 1.3rem',borderBottom:'1px solid var(--hair)',background:'var(--bg)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:'1rem',flexWrap:'wrap'}}><div style={{display:'flex',alignItems:'center',gap:'0.85rem',flexWrap:'wrap'}}><a href="/" className="nd-back-to-catalog">← Каталог</a><span style={{width:1,height:22,background:'var(--hair)'}}/><h1 style={{margin:0,fontFamily:'var(--nd-serif)',fontSize:'1.45rem'}}>{p.sessionName}</h1><span>{groups}</span>{days!==null&&<span>{days<=0?'Дедлайн истёк':`Дедлайн через ${days} дн.`}</span>}<span style={{color:p.sessionStatus==='active'?'var(--success)':'var(--text-muted)'}}>● {p.sessionStatus==='active'?'активна':'заморожена'}</span></div><div style={{position:'relative',display:'flex',alignItems:'center',gap:'1rem'}}>{p.viewer.role==='observer'?<span style={{color:'var(--success)',borderBottom:'1px solid var(--success)'}}>Вы наблюдаете</span>:<span>Вы — <strong>{p.viewer.displayName}</strong></span>}<button type="button" aria-label={`Участники: ${p.participants.length}`} onClick={()=>setOpen(!open)} style={{display:'flex',alignItems:'center',border:0,background:'transparent'}}>{p.participants.slice(0,5).map((x,i)=><span key={x.ref} aria-label={`${x.displayName} — ${x.online?'онлайн':'не в сети'}`} style={{marginLeft:i?-7:0,width:28,height:28,borderRadius:'50%',border:'2px solid var(--bg)',background:'var(--chip-bg)',display:'grid',placeItems:'center',color:x.online?'var(--success)':'var(--text-secondary)'}}>{x.displayName[0]}</span>)}<span style={{marginLeft:6}}>{p.participants.length}</span></button>{open&&<div role="dialog" aria-label="Участники" style={{position:'absolute',zIndex:5,right:0,top:'calc(100% + 0.5rem)',minWidth:220,padding:'0.75rem',background:'var(--bg-input)',border:'1px solid var(--border-strong)'}}>{p.participants.map(x=><div key={x.ref}><span style={{color:x.online?'var(--success)':'var(--text-muted)'}}>● </span>{x.displayName}</div>)}</div>}{!p.isImpersonating&&p.viewer.role==='active'&&<button type="button" onClick={leave} disabled={leaving} style={{border:0,background:'transparent',color:'var(--text-muted)'}}>{leaving?'Выходим…':'Покинуть'}</button>}</div></div>{error&&<p role="alert" style={{color:'var(--accent)'}}>{error}</p>}</header></>
}
