import { epic, feature } from 'allure-js-commons'
import { expect, test } from './fixtures'

test.beforeEach(async () => { await epic('Администрирование'); await feature('Модерация подборок') })
async function openModeration(page: import('@playwright/test').Page) { await page.goto('/admin?tab=collections'); await expect(page.getByTestId('admin-collections')).toBeVisible({ timeout: 15_000 }) }

test('владелец публикует новую подборку, и она остаётся опубликованной после reload', async ({ page, loginAsUser, loginAsAdmin, createTestBook, createTestCollection }) => { const books = [await createTestBook(), await createTestBook()]; const author = await loginAsUser(); const collection = await createTestCollection({ authorUserId: author.userId, bookIds: books.map(book => book.id), status: 'pending' }); await loginAsAdmin(); await openModeration(page); await page.getByTestId('queue-pending').getByText(collection.title).click(); await Promise.all([page.waitForResponse(response => response.url().includes(`/api/admin/collections/${collection.id}/actions`)), page.getByRole('button', { name: 'Опубликовать' }).click()]); await page.reload(); await expect(page.getByTestId('queue-published')).toContainText(collection.title) })

test('владелец отмечает изменённую подборку проверенной', async ({ page, loginAsUser, loginAsAdmin, createTestBook, createTestCollection }) => { const [kept, added] = [await createTestBook(), await createTestBook()]; const author = await loginAsUser(); const collection = await createTestCollection({ authorUserId: author.userId, bookIds: [kept.id, added.id], reviewedBookIds: [kept.id], editedAfterReview: true }); await loginAsAdmin(); await openModeration(page); const changed = page.getByTestId('queue-changed'); await expect(changed).toContainText(collection.title); await changed.getByText(collection.title).click(); await expect(page.getByTestId('diff-added')).toContainText(added.title); await page.getByRole('button', { name: 'Правка проверена' }).click(); await page.reload(); await expect(page.getByTestId('queue-changed')).not.toContainText(collection.title) })

test('скрытие с причиной сохраняется после reload', async ({ page, loginAsUser, loginAsAdmin, createTestBook, createTestCollection }) => { const books = [await createTestBook(), await createTestBook()]; const author = await loginAsUser(); const collection = await createTestCollection({ authorUserId: author.userId, bookIds: books.map(book => book.id) }); await loginAsAdmin(); await openModeration(page); await page.getByTestId('queue-published').getByText(collection.title).click(); await page.getByRole('button', { name: 'Скрыть с причиной' }).click(); await page.getByRole('dialog').getByRole('textbox').fill('E2E: добавьте описание'); await page.getByRole('button', { name: 'Отправить и скрыть' }).click(); await page.reload(); await expect(page.getByTestId('queue-rejected-hidden')).toContainText(collection.title) })
