// AUTO-GENERATED by scripts/build-routes.ts — do not edit by hand.
// Перегенерировать: npx ts-node --transpile-only -P tsconfig.scripts.json scripts/build-routes.ts
export const SITE_ROUTES: string[] = [
  "/",
  "/admin",
  "/admin/gallery",
  "/admin/sitemap",
  "/matching",
  "/matching/presentation",
  "/privacy",
  "/styleguide",
  "/vibe"
]
