// AUTO-GENERATED by scripts/build-routes.ts — do not edit by hand.
// Перегенерировать: npx ts-node --transpile-only -P tsconfig.scripts.json scripts/build-routes.ts
export const SITE_ROUTES: string[] = [
  "/",
  "/admin",
  "/admin/sitemap",
  "/books/[bookSlug]/my-summary/edit",
  "/books/[bookSlug]/summaries",
  "/matching",
  "/privacy",
  "/styleguide",
  "/summaries/[id]/edit",
  "/vibe"
]
