import type { DiffSummary } from './types'
export function pluralRu(n: number, one: string, few: string, many: string) { const mod10 = n % 10; const mod100 = n % 100; return mod10 === 1 && mod100 !== 11 ? one : mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20) ? few : many }
export const textsCount = (n: number) => `${n} ${pluralRu(n, 'текст', 'текста', 'текстов')}`
export const collectionsCount = (n: number) => `${n} ${pluralRu(n, 'подборка', 'подборки', 'подборок')}`
export function markdownExcerpt(markdown: string, max = 200) { const plain = markdown.replace(/<[^>]+>/g, ' ').replace(/!\[[^\]]*\]\([^)]*\)/g, ' ').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1').replace(/^\s{0,3}(#{1,6}|[-*+]|\d+\.)\s+/gm, '').replace(/[*_`>~]/g, '').replace(/\s+/g, ' ').trim(); if (plain.length <= max) return plain; const cut = plain.slice(0, max); const space = cut.lastIndexOf(' '); return `${(space > 0 ? cut.slice(0, space) : cut).trimEnd()}…` }
const startOfDay = (date: Date) => new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime()
export function formatChangedAt(date: Date, now: Date) { const days = Math.round((startOfDay(now) - startOfDay(date)) / 86_400_000); const relative = days <= 0 ? 'сегодня' : days === 1 ? 'вчера' : days < 14 ? `${days} ${pluralRu(days, 'день', 'дня', 'дней')} назад` : `${Math.floor(days / 7)} ${pluralRu(Math.floor(days / 7), 'неделю', 'недели', 'недель')} назад`; return { relative, absolute: date.toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' }) } }
export const formatDiffSummary = (summary: DiffSummary) => [summary.added > 0 ? `+${summary.added}` : null, summary.removed > 0 ? `−${summary.removed}` : null, summary.textChanged ? 'текст' : null, summary.orderChanged ? 'порядок' : null].filter(Boolean).join(' · ')
const issues: Record<string, string> = { title_required: 'Напишите название', title_too_long: 'Название длиннее 120 символов', description_required: 'Напишите описание', description_too_long: 'Описание длиннее 5000 символов', display_name_required: 'Укажите подпись', display_name_too_long: 'Подпись длиннее 60 символов', too_few_books: 'Нужно минимум два текста из каталога', too_many_books: 'В подборке не больше 50 текстов', duplicate_books: 'Один текст добавлен дважды', reason_required: 'Напишите причину', book_not_published: 'Эта книга ещё не опубликована в каталоге', migration_required: 'Подборки ещё не включены на сервере' }
export const collectionIssueText = (issue: string) => issues[issue] ?? 'Не удалось сохранить подборку'
