import { and, asc, eq, ilike, inArray, like, or } from 'drizzle-orm'
import { db } from '@/lib/db'
import { bookCollectionItems, bookCollections, books } from '@/lib/db/schema'
import { fetchBooksByIds, type BookWithCover } from '@/lib/books'
import { slugifyTitle, uniqueSlug } from '@/lib/slug'
import { CollectionError } from './errors'
import { canEditCollection, canViewCollection, collectionSortAt, normalizeBookIds, planAdminAction, planContentSave, planSubmit, validateCollectionContent } from './rules'
import type { AdminCollectionAction, CollectionBookSearchResult, CollectionListItem, CollectionRecord, CollectionSnapshot, CollectionStatus, CollectionViewer, EditorBook, MyCollectionItem } from './types'

type DbLike = typeof db; type Row = typeof bookCollections.$inferSelect
const toRecord = (row: Row, bookIds: string[]): CollectionRecord => ({ ...row, status: row.status as CollectionStatus, reviewedSnapshot: row.reviewedSnapshot as CollectionSnapshot | null, bookIds })
async function records(client: DbLike, rows: Row[]) { const ids = rows.map(row => row.id); const items = ids.length ? await client.select({ collectionId: bookCollectionItems.collectionId, bookId: bookCollectionItems.bookId }).from(bookCollectionItems).where(inArray(bookCollectionItems.collectionId, ids)).orderBy(asc(bookCollectionItems.collectionId), asc(bookCollectionItems.position)) : []; return rows.map(row => toRecord(row, items.filter(item => item.collectionId === row.id).map(item => item.bookId))) }
export async function loadCollectionById(id: string, client: DbLike = db) { const rows = await client.select().from(bookCollections).where(eq(bookCollections.id, id)).limit(1); return rows.length ? (await records(client, rows))[0] : null }
export async function loadCollectionBySlugOrId(ref: string, client: DbLike = db) { const rows = await client.select().from(bookCollections).where(eq(bookCollections.slug, ref)).limit(1); return rows.length ? (await records(client, rows))[0] : loadCollectionById(ref, client) }
export async function loadCollectionPageData(ref: string, viewer: CollectionViewer, client: DbLike = db): Promise<{ record: CollectionRecord; books: Array<{ book: BookWithCover; hiddenFromCatalog: boolean }> } | null> { const record = await loadCollectionBySlugOrId(ref, client); if (!record || !canViewCollection(record, viewer)) return null; const canSeeHidden = canEditCollection(record, viewer); const items = (await fetchBooksByIds(record.bookIds, client)).map(book => ({ book, hiddenFromCatalog: book.visibility !== 'published' })); return { record, books: items.filter(item => canSeeHidden || !item.hiddenFromCatalog) } }
export async function listPublishedCollections(client: DbLike = db): Promise<CollectionListItem[]> { const result = await records(client, await client.select().from(bookCollections).where(eq(bookCollections.status, 'published'))); const all = await fetchBooksByIds(result.flatMap(record => record.bookIds), client); const byId = new Map(all.map(book => [book.id, book])); return result.map(record => { const visible = record.bookIds.flatMap(id => { const book = byId.get(id); return book?.visibility === 'published' ? [book] : [] }); return { record, visible } }).filter(({ record, visible }) => !!record.slug && visible.length > 0).sort((a, b) => (collectionSortAt(b.record) ?? b.record.createdAt).getTime() - (collectionSortAt(a.record) ?? a.record.createdAt).getTime()).map(({ record, visible }) => ({ id: record.id, slug: record.slug as string, title: record.title, textsCount: visible.length, covers: visible.slice(0, 5).map(book => ({ id: book.id, title: book.name, author: book.author, coverUrl: book.coverUrl })), sortAt: (collectionSortAt(record) ?? record.createdAt).toISOString() })) }
export async function listMyCollections(userId: string, client: DbLike = db): Promise<MyCollectionItem[]> { const result = await records(client, await client.select().from(bookCollections).where(eq(bookCollections.authorUserId, userId))); const all = new Map((await fetchBooksByIds(result.flatMap(record => record.bookIds), client)).map(book => [book.id, book])); return result.sort((a,b) => b.updatedAt.getTime() - a.updatedAt.getTime()).map(record => ({ id: record.id, slug: record.slug, title: record.title, status: record.status, moderationReason: record.moderationReason, textsCount: record.bookIds.length, covers: record.bookIds.slice(0,8).flatMap(id => { const book=all.get(id); return book?[{id:book.id,title:book.name,author:book.author,coverUrl:book.coverUrl}]:[] }), changedAt: (record.editedAt ?? record.updatedAt).toISOString(), submittedAt: record.submittedAt?.toISOString() ?? null })) }
export async function searchPublishedBooks(query: string, client: DbLike = db): Promise<CollectionBookSearchResult[]> { const q=query.trim(); if(q.length<2)return []; const pattern=`%${q.replace(/[\\%_]/g, c => `\\${c}`)}%`; const rows=await client.select().from(books).where(and(eq(books.visibility,'published'),or(ilike(books.title,pattern),ilike(books.author,pattern)))).orderBy(asc(books.title)).limit(20); return rows.map(row=>({id:row.id,title:row.title,author:row.author,coverUrl:row.coverUrl,year:row.publishedDate.split('/').pop()?.trim()??'',isArticle:row.type==='article',clubStatus:row.readingStatus==='reading'||row.readingStatus==='read'?row.readingStatus:null})) }
export async function loadEditorBooks(bookIds: readonly string[], client: DbLike = db): Promise<EditorBook[]> { const all=await fetchBooksByIds(bookIds,client); const byId=new Map(all.map(book=>[book.id,book])); return bookIds.flatMap(id=>{const book=byId.get(id); return book?[{id:book.id,title:book.name,author:book.author,coverUrl:book.coverUrl,year:book.date.split('/').pop()?.trim()??'',isArticle:book.type==='Article',clubStatus:book.status??null,hiddenFromCatalog:book.visibility!=='published'}]:[]}) }
async function required(client: DbLike,id:string){const record=await loadCollectionById(id,client);if(!record)throw new CollectionError('not_found');return record}
export async function createDraftCollection(tx:DbLike,input:{authorUserId:string;title:string;now:Date}){const content={title:input.title,descriptionMarkdown:'',displayName:'',bookIds:[]};const issues=validateCollectionContent(content,'save');if(issues.length)throw new CollectionError('validation',{issues});const [row]=await tx.insert(bookCollections).values({authorUserId:input.authorUserId,title:input.title.trim(),createdAt:input.now,updatedAt:input.now}).returning();return toRecord(row,[])}
export async function saveCollectionContent(tx:DbLike,input:{id:string;content:CollectionSnapshot;by:'author'|'admin';now:Date}){const current=await required(tx,input.id);const issues=validateCollectionContent(input.content,'save');if(issues.length)throw new CollectionError('validation',{issues});const bookIds=normalizeBookIds(input.content.bookIds);const added=bookIds.filter(id=>!current.bookIds.includes(id));if(added.length){const published=await tx.select({id:books.id}).from(books).where(and(inArray(books.id,added),eq(books.visibility,'published')));if(published.length!==added.length)throw new CollectionError('book_not_published')}const {patch}=planContentSave(current,{...input.content,bookIds},input.by,input.now);await tx.update(bookCollections).set(patch).where(eq(bookCollections.id,input.id));if(bookIds.join('\n')!==current.bookIds.join('\n')){await tx.delete(bookCollectionItems).where(eq(bookCollectionItems.collectionId,input.id));if(bookIds.length)await tx.insert(bookCollectionItems).values(bookIds.map((bookId,index)=>({collectionId:input.id,bookId,position:index+1})))}return required(tx,input.id)}
export async function submitCollection(tx:DbLike,input:{id:string;now:Date}){const current=await required(tx,input.id);const found=await tx.select({id:books.id}).from(books).where(and(inArray(books.id,current.bookIds),eq(books.visibility,'published')));await tx.update(bookCollections).set(planSubmit(current,input.now,new Set(found.map(row=>row.id)))).where(eq(bookCollections.id,input.id));return required(tx,input.id)}
export async function applyAdminCollectionAction(tx:DbLike,input:{id:string;action:AdminCollectionAction;reason:string|null;now:Date}){const current=await required(tx,input.id);let slug:string|null=null;if((input.action==='publish'||input.action==='unhide')&&!current.slug){const base=slugifyTitle(current.title,'podborka');const taken=new Set((await tx.select({slug:bookCollections.slug}).from(bookCollections).where(like(bookCollections.slug,`${base}%`))).flatMap(row=>row.slug?[row.slug]:[]));slug=uniqueSlug(base,taken,new Set(['new']))}await tx.update(bookCollections).set(planAdminAction(current,input.action,{reason:input.reason,now:input.now,slug})).where(eq(bookCollections.id,input.id));return required(tx,input.id)}
export async function deleteCollection(tx:DbLike,id:string){await tx.delete(bookCollections).where(eq(bookCollections.id,id))}
