import { CollectionError } from './errors'
import { COLLECTION_LIMITS, type AdminCollectionAction, type CollectionAction, type CollectionRecord, type CollectionSnapshot, type CollectionStatus, type CollectionViewer } from './types'

type Owned = Pick<CollectionRecord, 'authorUserId' | 'status'>
export const isCollectionOwner = (record: Pick<CollectionRecord, 'authorUserId'>, viewer: CollectionViewer) => viewer.userId !== null && viewer.userId === record.authorUserId
export const canViewCollection = (record: Owned, viewer: CollectionViewer) => record.status === 'published' || viewer.isAdmin || isCollectionOwner(record, viewer)
export const canEditCollection = (record: Owned, viewer: CollectionViewer) => viewer.isAdmin || isCollectionOwner(record, viewer)
export const canDeleteCollection = (record: Owned, viewer: CollectionViewer) => viewer.isAdmin || (isCollectionOwner(record, viewer) && record.status !== 'published')
export function normalizeBookIds(ids: readonly string[]) { const seen = new Set<string>(); return ids.flatMap(raw => { const id = raw.trim(); if (!id || seen.has(id)) return []; seen.add(id); return [id] }) }
export type CollectionValidationIssue = 'title_required' | 'title_too_long' | 'description_required' | 'description_too_long' | 'display_name_required' | 'display_name_too_long' | 'too_few_books' | 'too_many_books' | 'duplicate_books'
export function validateCollectionContent(content: CollectionSnapshot, mode: 'save' | 'submit', publicBookIds: ReadonlySet<string> = new Set()): CollectionValidationIssue[] {
  const issues: CollectionValidationIssue[] = []; const title = content.title.trim(); const displayName = content.displayName.trim()
  if (!title) issues.push('title_required'); if (title.length > COLLECTION_LIMITS.titleMax) issues.push('title_too_long'); if (content.descriptionMarkdown.length > COLLECTION_LIMITS.descriptionMax) issues.push('description_too_long'); if (displayName.length > COLLECTION_LIMITS.displayNameMax) issues.push('display_name_too_long'); if (content.bookIds.length > COLLECTION_LIMITS.booksMax) issues.push('too_many_books'); if (normalizeBookIds(content.bookIds).length !== content.bookIds.length) issues.push('duplicate_books')
  if (mode === 'submit') { if (!content.descriptionMarkdown.trim()) issues.push('description_required'); if (!displayName) issues.push('display_name_required'); if (content.bookIds.filter(id => publicBookIds.has(id)).length < COLLECTION_LIMITS.booksMinToSubmit) issues.push('too_few_books') }
  return issues
}
export const snapshotOf = (content: CollectionSnapshot): CollectionSnapshot => ({ title: content.title, descriptionMarkdown: content.descriptionMarkdown, displayName: content.displayName, bookIds: [...content.bookIds] })
export type CollectionEditKind = 'none' | 'order_only' | 'content'
export function classifyCollectionEdit(prev: CollectionSnapshot, next: CollectionSnapshot): CollectionEditKind { if (prev.title !== next.title || prev.descriptionMarkdown !== next.descriptionMarkdown || prev.displayName !== next.displayName || prev.bookIds.length !== next.bookIds.length || next.bookIds.some(id => !prev.bookIds.includes(id))) return 'content'; return prev.bookIds.some((id, i) => next.bookIds[i] !== id) ? 'order_only' : 'none' }
export const isChangedSinceReview = (r: Pick<CollectionRecord, 'status' | 'editedAt' | 'reviewedAt'>) => r.status === 'published' && !!r.editedAt && (!r.reviewedAt || r.editedAt > r.reviewedAt)
export const collectionSortAt = (r: Pick<CollectionRecord, 'publishedAt' | 'editedAt'>) => { const values = [r.publishedAt, r.editedAt].filter((x): x is Date => x !== null); return values.length ? new Date(Math.max(...values.map(x => x.getTime()))) : null }
const transitions: Record<CollectionAction, { from: CollectionStatus[]; to: CollectionStatus }> = { submit: { from: ['draft', 'rejected', 'hidden'], to: 'pending' }, publish: { from: ['pending'], to: 'published' }, reject: { from: ['pending'], to: 'rejected' }, mark_reviewed: { from: ['published'], to: 'published' }, hide: { from: ['published'], to: 'hidden' }, unhide: { from: ['hidden'], to: 'published' } }
export function nextCollectionStatus(status: CollectionStatus, action: CollectionAction) { const transition = transitions[action]; if (!transition.from.includes(status)) throw new CollectionError('invalid_transition', { status, action }); return transition.to }
export const actionRequiresReason = (action: CollectionAction) => action === 'reject' || action === 'hide'
export function planContentSave(current: CollectionRecord, next: CollectionSnapshot, by: 'author' | 'admin', now: Date) { const normalized = { title: next.title.trim(), descriptionMarkdown: next.descriptionMarkdown, displayName: next.displayName.trim(), bookIds: normalizeBookIds(next.bookIds) }; const kind = classifyCollectionEdit(snapshotOf(current), normalized); const patch: { title: string; descriptionMarkdown: string; displayName: string; updatedAt: Date; editedAt?: Date; reviewedAt?: Date; reviewedSnapshot?: CollectionSnapshot } = { ...normalized, updatedAt: now }; delete (patch as Partial<CollectionSnapshot>).bookIds; if (by === 'author' && kind === 'content') patch.editedAt = now; if (by === 'admin' && current.status === 'published') { patch.reviewedAt = now; patch.reviewedSnapshot = normalized }; return { kind, patch } }
export function planSubmit(current: CollectionRecord, now: Date, publicBookIds: ReadonlySet<string>) { const issues = validateCollectionContent(snapshotOf(current), 'submit', publicBookIds); if (issues.length) throw new CollectionError('validation', { issues }); return { status: nextCollectionStatus(current.status, 'submit'), submittedAt: now, updatedAt: now } }
export function planAdminAction(current: CollectionRecord, action: AdminCollectionAction, input: { reason: string | null; now: Date; slug: string | null }) { const status = nextCollectionStatus(current.status, action); const reason = input.reason?.trim() ?? ''; if (actionRequiresReason(action) && !reason) throw new CollectionError('validation', { issues: ['reason_required'] }); const patch: { status: CollectionStatus; updatedAt: Date; moderationReason?: string | null; publishedAt?: Date; reviewedAt?: Date; reviewedSnapshot?: CollectionSnapshot; slug?: string } = { status, updatedAt: input.now }; if (action === 'publish' || action === 'unhide') { patch.moderationReason = null; patch.publishedAt = input.now; patch.reviewedAt = input.now; patch.reviewedSnapshot = snapshotOf(current); if (!current.slug) { if (!input.slug) throw new Error('slug is required for the first publication'); patch.slug = input.slug } } else if (action === 'reject' || action === 'hide') patch.moderationReason = reason; else { patch.reviewedAt = input.now; patch.reviewedSnapshot = snapshotOf(current) }; return patch }
