/* eslint-disable no-console */
/**
 * Сканирует app/**\/page.tsx и генерирует список публичных роутов сайта
 * в lib/site-routes.generated.ts (для страницы /admin/sitemap).
 *
 *   npx ts-node --transpile-only -P tsconfig.scripts.json scripts/build-routes.ts
 *
 * Запускать при добавлении/удалении страниц. Файл коммитится.
 */
import fs from 'node:fs'
import path from 'node:path'

const APP_DIR = path.resolve(__dirname, '..', 'app')
const OUT = path.resolve(__dirname, '..', 'lib', 'site-routes.generated.ts')

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'api') continue // API-роуты не страницы
      walk(full, acc)
    } else if (entry.name === 'page.tsx') {
      acc.push(full)
    }
  }
  return acc
}

function toRoute(file: string): string {
  const rel = path.relative(APP_DIR, path.dirname(file))
  if (rel === '') return '/'
  const segments = rel
    .split(path.sep)
    .filter((s) => !(s.startsWith('(') && s.endsWith(')'))) // route groups не влияют на URL
  return '/' + segments.join('/')
}

const routes = Array.from(new Set(walk(APP_DIR).map(toRoute))).sort((a, b) => a.localeCompare(b))

const body =
  `// AUTO-GENERATED by scripts/build-routes.ts — do not edit by hand.\n` +
  `// Перегенерировать: npx ts-node --transpile-only -P tsconfig.scripts.json scripts/build-routes.ts\n` +
  `export const SITE_ROUTES: string[] = ${JSON.stringify(routes, null, 2)}\n`

fs.writeFileSync(OUT, body)
console.log(`Готово: ${routes.length} роутов → ${OUT}`)
for (const r of routes) console.log('  ' + r)
