#!/usr/bin/env npx tsx
// AUTO-RUN: npx tsx scripts/generate-pseudonym-declensions.ts
// Writes lib/matching/pseudonym-declensions.generated.ts

import * as RussianNouns from 'russian-nouns-js'
import { writeFileSync } from 'fs'
import { join } from 'path'
import { ANIMALS } from '../lib/matching/pseudonyms'
import { PSEUDONYM_GENDER } from '../lib/matching/pseudonym-gender'

const rne = new RussianNouns.Engine()
const Case = RussianNouns.Case
const Gender = RussianNouns.Gender

const GENDER_MAP: Record<'м' | 'ж' | 'с', string> = {
  'м': Gender.MASCULINE,
  'ж': Gender.FEMININE,
  'с': Gender.NEUTER,
}

export interface PseudonymDeclension {
  nom: string   // именительный (= имя)
  gen: string   // родительный: у Барсука
  dat: string   // дательный: Барсуку
  acc: string   // винительный: вижу Барсука
  ins: string   // творительный: с Барсуком
  pre: string   // предложный: о Барсуке
  gender: 'м' | 'ж' | 'с'
}

const result: Record<string, PseudonymDeclension> = {}

for (const name of ANIMALS) {
  const g = PSEUDONYM_GENDER[name]
  if (!g) {
    console.warn(`No gender for ${name}, skipping`)
    continue
  }
  const lemma = RussianNouns.Lemma.create({ text: name, gender: GENDER_MAP[g] })
  const decline = (c: string) => {
    const forms = rne.decline(lemma, c)
    return forms[0] ?? name
  }
  result[name] = {
    nom: name,
    gen: decline(Case.GENITIVE),
    dat: decline(Case.DATIVE),
    acc: decline(Case.ACCUSATIVE),
    ins: decline(Case.INSTRUMENTAL),
    pre: decline(Case.PREPOSITIONAL),
    gender: g,
  }
}

const lines = Object.entries(result).map(([name, d]) =>
  `  ${JSON.stringify(name)}: ${JSON.stringify(d)},`
)

const output = `// AUTO-GENERATED by scripts/generate-pseudonym-declensions.ts — do not edit by hand.
// Run: npx tsx scripts/generate-pseudonym-declensions.ts
import type { PseudonymDeclension } from './pseudonym-declension'
export { type PseudonymDeclension }

export const PSEUDONYM_DECLENSIONS: Record<string, PseudonymDeclension> = {
${lines.join('\n')}
}
`

const outPath = join(__dirname, '../lib/matching/pseudonym-declensions.generated.ts')
writeFileSync(outPath, output, 'utf8')
console.log(`Written ${Object.keys(result).length} entries to ${outPath}`)
