/* eslint-disable no-console */
/**
 * Generates drizzle/0021_books_catalog.sql from data/books-catalog-snapshot.json.
 * Run after scripts/books-catalog-audit.ts to keep migration in sync with prod snapshot.
 */

import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

interface BookSeed {
  uuid: string
  source: 'sheets_import' | 'submission'
  legacySheetsRowId: string | null
  sourceSubmissionId: string | null
  canonicalKey: string
  title: string
  author: string
  tags: string[]
  type: 'book' | 'article'
  size: string
  pages: number | null
  publishedDate: string
  textUrl: string
  description: string
  coverUrl: string | null
  whyRead: string | null
  recommendationLink: string | null
  readingStatus: 'reading' | 'read' | null
  isNew: boolean
  visibility: 'published' | 'hidden'
  sortOrder: number
  publishedAtIso: string
}

interface Mapping {
  legacySource: 'sheets' | 'submission' | 'book_name'
  legacyId: string
  legacyTitle: string
  legacyAuthor: string | null
  bookUuid: string | null
  confidence: 'exact' | 'normalized' | 'manual' | 'unmatched'
  resolution: string
}

interface Snapshot {
  books: BookSeed[]
  legacyMappings: Mapping[]
}

function sqlString(v: string | null | undefined): string {
  if (v === null || v === undefined) return 'NULL'
  return `'${v.replace(/'/g, "''")}'`
}

function sqlBool(v: boolean): string {
  return v ? 'TRUE' : 'FALSE'
}

function sqlJsonbArray(arr: string[]): string {
  return `'${JSON.stringify(arr).replace(/'/g, "''")}'::jsonb`
}

function sqlInt(v: number | null): string {
  return v === null || v === undefined ? 'NULL' : String(v)
}

function main() {
  const root = path.resolve(__dirname, '..')
  const snapshot: Snapshot = JSON.parse(
    fs.readFileSync(path.join(root, 'data', 'books-catalog-snapshot.json'), 'utf8'),
  )

  const out: string[] = []
  out.push(`-- Books catalog refactor: replaces Sheets-driven catalog with first-class books table.`)
  out.push(`-- Seeded from data/books-catalog-snapshot.json (generated by scripts/books-catalog-audit.ts).`)
  out.push(``)
  out.push(`-- 1. New tables`)
  out.push(`CREATE TABLE IF NOT EXISTS "books" (`)
  out.push(`  "id" text PRIMARY KEY NOT NULL,`)
  out.push(`  "canonical_key" text,`)
  out.push(`  "title" text NOT NULL,`)
  out.push(`  "author" text NOT NULL DEFAULT '',`)
  out.push(`  "tags" jsonb NOT NULL DEFAULT '[]'::jsonb,`)
  out.push(`  "type" text NOT NULL DEFAULT 'book',`)
  out.push(`  "size" text NOT NULL DEFAULT '',`)
  out.push(`  "pages" integer,`)
  out.push(`  "published_date" text NOT NULL DEFAULT '',`)
  out.push(`  "text_url" text NOT NULL DEFAULT '',`)
  out.push(`  "description" text NOT NULL DEFAULT '',`)
  out.push(`  "cover_url" text,`)
  out.push(`  "why_read" text,`)
  out.push(`  "recommendation_link" text,`)
  out.push(`  "reading_status" text,`)
  out.push(`  "visibility" text NOT NULL DEFAULT 'hidden',`)
  out.push(`  "is_new" boolean NOT NULL DEFAULT FALSE,`)
  out.push(`  "sort_order" integer NOT NULL DEFAULT 0,`)
  out.push(`  "source" text NOT NULL DEFAULT 'admin',`)
  out.push(`  "source_submission_id" text,`)
  out.push(`  "legacy_sheets_row_id" text,`)
  out.push(`  "created_at" timestamp NOT NULL DEFAULT now(),`)
  out.push(`  "updated_at" timestamp NOT NULL DEFAULT now(),`)
  out.push(`  "published_at" timestamp,`)
  out.push(`  "hidden_at" timestamp,`)
  out.push(`  "archived_at" timestamp,`)
  out.push(`  CONSTRAINT "books_visibility_check" CHECK ("visibility" IN ('hidden','published')),`)
  out.push(`  CONSTRAINT "books_type_check" CHECK ("type" IN ('book','article')),`)
  out.push(`  CONSTRAINT "books_source_check" CHECK ("source" IN ('admin','submission','sheets_import')),`)
  out.push(`  CONSTRAINT "books_reading_status_check" CHECK ("reading_status" IS NULL OR "reading_status" IN ('reading','read'))`)
  out.push(`);`)
  out.push(`CREATE INDEX IF NOT EXISTS "books_visibility_idx" ON "books"("visibility");`)
  out.push(`CREATE INDEX IF NOT EXISTS "books_source_submission_id_idx" ON "books"("source_submission_id");`)
  out.push(`CREATE UNIQUE INDEX IF NOT EXISTS "books_source_submission_id_unique" ON "books"("source_submission_id") WHERE "source_submission_id" IS NOT NULL;`)
  out.push(`CREATE INDEX IF NOT EXISTS "books_canonical_key_idx" ON "books"("canonical_key");`)
  out.push(`CREATE INDEX IF NOT EXISTS "books_sort_order_idx" ON "books"("sort_order");`)
  out.push(``)
  out.push(`CREATE TABLE IF NOT EXISTS "legacy_book_mappings" (`)
  out.push(`  "id" text PRIMARY KEY NOT NULL,`)
  out.push(`  "legacy_source" text NOT NULL,`)
  out.push(`  "legacy_id" text NOT NULL,`)
  out.push(`  "legacy_title" text,`)
  out.push(`  "legacy_author" text,`)
  out.push(`  "book_id" text REFERENCES "books"("id") ON DELETE SET NULL,`)
  out.push(`  "confidence" text NOT NULL,`)
  out.push(`  "resolution" text,`)
  out.push(`  "created_at" timestamp NOT NULL DEFAULT now()`)
  out.push(`);`)
  out.push(`CREATE UNIQUE INDEX IF NOT EXISTS "legacy_book_mappings_source_id_idx" ON "legacy_book_mappings"("legacy_source","legacy_id");`)
  out.push(`CREATE INDEX IF NOT EXISTS "legacy_book_mappings_book_id_idx" ON "legacy_book_mappings"("book_id");`)
  out.push(``)

  // 2. Seed books
  out.push(`-- 2. Seed books from prod snapshot (idempotent via ON CONFLICT)`)
  for (const b of snapshot.books) {
    out.push(`INSERT INTO "books" (`)
    out.push(`  "id","canonical_key","title","author","tags","type","size","pages","published_date","text_url",`)
    out.push(`  "description","cover_url","why_read","recommendation_link","reading_status","visibility","is_new",`)
    out.push(`  "sort_order","source","source_submission_id","legacy_sheets_row_id","published_at"`)
    out.push(`) VALUES (`)
    out.push(`  ${sqlString(b.uuid)}, ${sqlString(b.canonicalKey)}, ${sqlString(b.title)}, ${sqlString(b.author)}, ${sqlJsonbArray(b.tags)}, ${sqlString(b.type)}, ${sqlString(b.size)}, ${sqlInt(b.pages)}, ${sqlString(b.publishedDate)}, ${sqlString(b.textUrl)},`)
    out.push(`  ${sqlString(b.description)}, ${sqlString(b.coverUrl)}, ${sqlString(b.whyRead)}, ${sqlString(b.recommendationLink)}, ${sqlString(b.readingStatus)}, ${sqlString(b.visibility)}, ${sqlBool(b.isNew)},`)
    out.push(`  ${b.sortOrder}, ${sqlString(b.source)}, ${sqlString(b.sourceSubmissionId)}, ${sqlString(b.legacySheetsRowId)}, ${sqlString(b.publishedAtIso)}::timestamp`)
    out.push(`) ON CONFLICT ("id") DO NOTHING;`)
  }
  out.push(``)

  // 3. Seed legacy mappings
  out.push(`-- 3. Seed legacy mappings`)
  for (const m of snapshot.legacyMappings) {
    out.push(`INSERT INTO "legacy_book_mappings" ("id","legacy_source","legacy_id","legacy_title","legacy_author","book_id","confidence","resolution")`)
    const id = `mig-${m.legacySource}-${crypto.createHash('sha256').update(m.legacyId).digest('hex').slice(0, 16)}`
    out.push(`VALUES (${sqlString(id)}, ${sqlString(m.legacySource)}, ${sqlString(m.legacyId)}, ${sqlString(m.legacyTitle)}, ${sqlString(m.legacyAuthor)}, ${sqlString(m.bookUuid)}, ${sqlString(m.confidence)}, ${sqlString(m.resolution)})`)
    out.push(`ON CONFLICT ("legacy_source","legacy_id") DO UPDATE SET "book_id"=EXCLUDED."book_id", "confidence"=EXCLUDED."confidence";`)
  }
  out.push(``)

  // 4. book_submissions.book_id
  out.push(`-- 4. book_submissions.book_id (FK to books)`)
  out.push(`ALTER TABLE "book_submissions" ADD COLUMN IF NOT EXISTS "book_id" text;`)
  out.push(`DO $$ BEGIN`)
  out.push(`  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'book_submissions_book_id_fk') THEN`)
  out.push(`    ALTER TABLE "book_submissions" ADD CONSTRAINT "book_submissions_book_id_fk" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE SET NULL;`)
  out.push(`  END IF;`)
  out.push(`END $$;`)
  out.push(`CREATE INDEX IF NOT EXISTS "book_submissions_book_id_idx" ON "book_submissions"("book_id");`)
  out.push(`-- backfill book_submissions.book_id from books.source_submission_id`)
  out.push(`UPDATE "book_submissions" bs SET "book_id" = b."id"`)
  out.push(`FROM "books" b WHERE b."source_submission_id" = bs."id" AND bs."book_id" IS NULL;`)
  out.push(``)

  // 5. signup_books: add nullable book_id, backfill. Keep book_name for transition.
  out.push(`-- 5. signup_books.book_id (additive — keep book_name during transition)`)
  out.push(`ALTER TABLE "signup_books" ADD COLUMN IF NOT EXISTS "book_id" text;`)
  out.push(`UPDATE "signup_books" sb SET "book_id" = lbm."book_id"`)
  out.push(`FROM "legacy_book_mappings" lbm`)
  out.push(`WHERE lbm."legacy_source" = 'book_name' AND lbm."legacy_id" = sb."book_name" AND sb."book_id" IS NULL;`)
  out.push(`CREATE INDEX IF NOT EXISTS "signup_books_book_id_idx" ON "signup_books"("book_id");`)
  out.push(`DO $$ BEGIN`)
  out.push(`  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'signup_books_book_id_fk') THEN`)
  out.push(`    ALTER TABLE "signup_books" ADD CONSTRAINT "signup_books_book_id_fk" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE;`)
  out.push(`  END IF;`)
  out.push(`END $$;`)
  out.push(``)

  // 6. book_priorities: same shape change (additive)
  out.push(`-- 6. book_priorities.book_id (additive — keep book_name during transition)`)
  out.push(`ALTER TABLE "book_priorities" ADD COLUMN IF NOT EXISTS "book_id" text;`)
  out.push(`UPDATE "book_priorities" bp SET "book_id" = lbm."book_id"`)
  out.push(`FROM "legacy_book_mappings" lbm`)
  out.push(`WHERE lbm."legacy_source" = 'book_name' AND lbm."legacy_id" = bp."book_name" AND bp."book_id" IS NULL;`)
  out.push(`CREATE INDEX IF NOT EXISTS "book_priorities_book_id_idx" ON "book_priorities"("book_id");`)
  out.push(`DO $$ BEGIN`)
  out.push(`  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'book_priorities_book_id_fk') THEN`)
  out.push(`    ALTER TABLE "book_priorities" ADD CONSTRAINT "book_priorities_book_id_fk" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE;`)
  out.push(`  END IF;`)
  out.push(`END $$;`)
  out.push(``)

  out.push(`-- Note: book_statuses, book_new_flags, signup_books.book_name and book_priorities.book_name`)
  out.push(`-- are removed in a separate cleanup migration (0022_books_catalog_cleanup.sql) after the new`)
  out.push(`-- code paths are deployed and soaked.`)

  const outPath = path.join(root, 'drizzle', '0021_books_catalog.sql')
  fs.writeFileSync(outPath, out.join('\n') + '\n')

  // Cleanup migration (0022) — applied AFTER new code is live and signup_books / book_priorities
  // are fully migrated to book_id reads/writes.
  const cleanup: string[] = []
  cleanup.push(`-- Stage 6 final cleanup — apply after the runtime is fully on book_id`)
  cleanup.push(`-- (signup_books / book_priorities reads/writes go through book_id). The earlier`)
  cleanup.push(`-- 0022_drop_book_statuses_flags.sql already removed book_statuses / book_new_flags.`)
  cleanup.push(``)
  cleanup.push(`-- 1. signup_books: enforce book_id NOT NULL, switch primary key, drop book_name.`)
  cleanup.push(`DELETE FROM "signup_books" WHERE "book_id" IS NULL;`)
  cleanup.push(`ALTER TABLE "signup_books" ALTER COLUMN "book_id" SET NOT NULL;`)
  cleanup.push(`ALTER TABLE "signup_books" DROP CONSTRAINT IF EXISTS "signup_books_user_id_book_name_pk";`)
  cleanup.push(`ALTER TABLE "signup_books" ADD CONSTRAINT "signup_books_user_id_book_id_pk" PRIMARY KEY ("user_id","book_id");`)
  cleanup.push(`ALTER TABLE "signup_books" DROP COLUMN IF EXISTS "book_name";`)
  cleanup.push(``)
  cleanup.push(`-- 2. book_priorities: same shape change.`)
  cleanup.push(`DELETE FROM "book_priorities" WHERE "book_id" IS NULL;`)
  cleanup.push(`ALTER TABLE "book_priorities" ALTER COLUMN "book_id" SET NOT NULL;`)
  cleanup.push(`ALTER TABLE "book_priorities" DROP CONSTRAINT IF EXISTS "book_priorities_user_id_book_name_pk";`)
  cleanup.push(`ALTER TABLE "book_priorities" ADD CONSTRAINT "book_priorities_user_id_book_id_pk" PRIMARY KEY ("user_id","book_id");`)
  cleanup.push(`ALTER TABLE "book_priorities" DROP COLUMN IF EXISTS "book_name";`)
  cleanup.push(``)
  cleanup.push(`-- 3. Optional: drop legacy_book_mappings once no code reads it.`)
  cleanup.push(`-- DROP TABLE IF EXISTS "legacy_book_mappings";`)

  const cleanupPath = path.join(root, 'drizzle', '0023_books_catalog_drop_book_name.sql')
  fs.writeFileSync(cleanupPath, cleanup.join('\n') + '\n')
  console.log(`Wrote ${outPath} (${snapshot.books.length} books, ${snapshot.legacyMappings.length} mappings)`)
  console.log(`Wrote ${cleanupPath} (cleanup follow-up)`)
}

main()
