// AUTO-GENERATED by scripts/fetch-pseudonym-photos.ts — do not edit by hand.
export interface PseudonymPhoto { file: string; author: string; license: string; sourceUrl: string }
export const SPECIES_PHOTOS: Record<string, PseudonymPhoto> = {
  "Барсук": {
    "file": "/matching/species/barsuk.webp",
    "author": "Byrdyak",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%BE%D1%80%D1%81%D1%83%D0%BA.jpg"
  },
  "Бегемот": {
    "file": "/matching/species/begemot.webp",
    "author": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hipop%C3%B3tamo_(Hippopotamus_amphibius),_parque_nacional_de_Chobe,_Botsuana,_2018-07-28,_DD_82.jpg"
  },
  "Белка": {
    "file": "/matching/species/belka.webp",
    "author": "NPS",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aberts_squirrel.jpg"
  },
  "Бобёр": {
    "file": "/matching/species/bobyor.webp",
    "author": "Dion Art",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%9E%D0%B1%D1%8B%D0%BA%D0%BD%D0%BE%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B1%D0%BE%D0%B1%D1%80_(Castor_fiber),_%D0%9F%D0%BE%D0%BA%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%BE%D0%B5-%D0%A1%D1%82%D1%80%D0%B5%D1%88%D0%BD%D0%B5%D0%B2%D0%BE.jpg"
  },
  "Бурундук": {
    "file": "/matching/species/burunduk.webp",
    "author": "Phil Armitage",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tamias_minimus.jpg"
  },
  "Верблюд": {
    "file": "/matching/species/verblyud.webp",
    "author": "Готлиб XI",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Montage_of_Camelus.png"
  },
  "Волк": {
    "file": "/matching/species/volk.webp",
    "author": "User:Mas3cf",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eurasian_wolf_2.jpg"
  },
  "Выдра": {
    "file": "/matching/species/vydra.webp",
    "author": "Peter Trimming from Croydon, England",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Young_Otter_(1)_(5878286924).jpg"
  },
  "Выхухоль": {
    "file": "/matching/species/vyhuhol.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Desmana_moschata_MHNT.INS.10.jpg"
  },
  "Гепард": {
    "file": "/matching/species/gepard.webp",
    "author": "Mukul2u",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cheetah_Kruger.jpg"
  },
  "Горностай": {
    "file": "/matching/species/gornostay.webp",
    "author": "cazalegg",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stoat_-_Mustela_erminea_-_54888079091.jpg"
  },
  "Гризли": {
    "file": "/matching/species/grizli.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lightmatter_Alaskan_brownbear.jpg"
  },
  "Дикобраз": {
    "file": "/matching/species/dikobraz.webp",
    "author": "Quartl",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hystrix_cristata_qtl1.jpg"
  },
  "Енот": {
    "file": "/matching/species/enot.webp",
    "author": "Alexas_Fotos",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raccoon_on_Log.jpg"
  },
  "Ёж": {
    "file": "/matching/species/yozh.webp",
    "author": "Jörg Hempel",
    "license": "CC BY-SA 2.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Erinaceus_europaeus_LC0119.jpg"
  },
  "Зебра": {
    "file": "/matching/species/zebra.webp",
    "author": "Muhammad Mahdi Karim",
    "license": "GFDL 1.2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Plains_Zebra_Equus_quagga.jpg"
  },
  "Зубр": {
    "file": "/matching/species/zubr.webp",
    "author": "Michael Gäbler",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bison_bonasus_(Linnaeus_1758).jpg"
  },
  "Зяблик": {
    "file": "/matching/species/zyablik.webp",
    "author": "MichaelMaggs – Edited (sharpened, down-sampled, contrast corrected, noise removed) by: Arad",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fringilla_coelebs_chaffinch_male_edit2.jpg"
  },
  "Кабан": {
    "file": "/matching/species/kaban.webp",
    "author": "4028mdk09",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ausgewachsenes_Wildschwein_beim_Suhlen.JPG"
  },
  "Кабарга": {
    "file": "/matching/species/kabarga.webp",
    "author": "Николай Усик / http://paradoxusik.livejournal.com/",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moschus_moschiferus_in_Plzen_zoo_(12.02.2011).jpg"
  },
  "Кенгуру": {
    "file": "/matching/species/kenguru.webp",
    "author": "fir0002 flagstaffotos [at] gmail.com Canon 20D + Canon 400mm f/5.6 L",
    "license": "GFDL 1.2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eastern_grey_kangaroo_dec07_02.jpg"
  },
  "Кит": {
    "file": "/matching/species/kit.webp",
    "author": "The original uploader was Zorankovacevic at English Wikipedia.",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jumping_Humpback_whale.jpg"
  },
  "Козуля": {
    "file": "/matching/species/kozulya.webp",
    "author": "Anastasiya Lvova",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Three_kozuli.jpg"
  },
  "Кот": {
    "file": "/matching/species/kot.webp",
    "author": "Alvesgaspar, Martin Bahmann, Hisashi, Von.grzanka, Dovenetel",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cat_poster_1.jpg"
  },
  "Кролик": {
    "file": "/matching/species/krolik.webp",
    "author": "Stolz, Gary M.",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sylvilagus_audubonii.jpg"
  },
  "Кугуар": {
    "file": "/matching/species/kuguar.webp",
    "author": "Carlos",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Puma_-_49044464307.jpg"
  },
  "Куница": {
    "file": "/matching/species/kunitsa.webp",
    "author": "caroline legg",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pine_Marten_(48941946582).jpg"
  },
  "Лемур": {
    "file": "/matching/species/lemur.webp",
    "author": "Andriaholinirina, N., Fausser, J.-L., Roos, C., Zinner, D., Thalmann, U., Rabarivola, C., Ravoarimanana, I., Ganzhorn, J.U., Meier, B., Hilgartner, R., Walter, L., Zaramody, A., Langer, C., Hahn, T., Zimmermann, E., Radespiel, U., Craul, M., Tomiuk, J., Tattersall, I. &amp; Rumpler, Y.",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lepilemur_aeeclis_c.PNG"
  },
  "Лиса": {
    "file": "/matching/species/lisa.webp",
    "author": "4028mdk09",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tiergarten_Worms_Rotfuchs_2011.JPG"
  },
  "Лось": {
    "file": "/matching/species/los.webp",
    "author": "USDA Forest Service",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moose_superior.jpg"
  },
  "Лошадь": {
    "file": "/matching/species/loshad.webp",
    "author": "Thomas Reich",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pernod_Al_Ariba_0046b.jpg"
  },
  "Лягушка": {
    "file": "/matching/species/lyagushka.webp",
    "author": "Grand-Duc, Niabot (edit)",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rana_esculenta_on_Nymphaea_edit.JPG"
  },
  "Маралка": {
    "file": "/matching/species/maralka.webp",
    "author": "Lviatour",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cervus_elaphus_Luc_Viatour_6.jpg"
  },
  "Медведь": {
    "file": "/matching/species/medved.webp",
    "author": "MathKnight",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ursidae-01.jpg"
  },
  "Мышь": {
    "file": "/matching/species/mysh.webp",
    "author": "Rasbak",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apodemus_sylvaticus_bosmuis.jpg"
  },
  "Нарвал": {
    "file": "/matching/species/narval.webp",
    "author": "пресс-служба ПАО \"Газпром нефть\"",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%9D%D0%B0%D1%80%D0%B2%D0%B0%D0%BB_%D0%B2_%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%BE%D0%B9_%D0%90%D1%80%D0%BA%D1%82%D0%B8%D0%BA%D0%B5.jpg"
  },
  "Норка": {
    "file": "/matching/species/norka.webp",
    "author": "Needsmoreritalin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MinkforWiki.jpg"
  },
  "Нутрия": {
    "file": "/matching/species/nutriya.webp",
    "author": "No machine-readable author provided. Schieber assumed (based on copyright claims).",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Myocastor_coypus.jpg"
  },
  "Овца": {
    "file": "/matching/species/ovtsa.webp",
    "author": "André Karwath aka Aka",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ovis_orientalis_aries_%27Skudde%27_(aka).jpg"
  },
  "Олень": {
    "file": "/matching/species/olen.webp",
    "author": "This image is a derivative work of the following images: File:White-tailed deer.jpg (USDA photo by Scott Bauer) File:RangiferTarandus.jpg (uploaded by User:Sydpolen) File:Red deer stag 2009 denmark.jpg (uploaded by User:Atomicbre) File:The barasingha.jpg (uploaded by aloshbennett) File:Dama dama 002.jpg (uploaded by User:Lily_M))",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Family_Cervidae_five_species.jpg"
  },
  "Осёл": {
    "file": "/matching/species/osyol.webp",
    "author": "Adrian Pingstone",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Donkey_in_Clovelly,_North_Devon,_England.jpg"
  },
  "Пантера": {
    "file": "/matching/species/pantera.webp",
    "author": "Termininja",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_Diversity.jpg"
  },
  "Панда": {
    "file": "/matching/species/panda.webp",
    "author": "User Jcwf on nl.wikipedia",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panda_closeup.jpg"
  },
  "Песец": {
    "file": "/matching/species/pesets.webp",
    "author": "Emma",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Arctic_fox_(6375719339).jpg"
  },
  "Пингвин": {
    "file": "/matching/species/pingvin.webp",
    "author": "PaleoMatt",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Penguins_collage.png"
  },
  "Пума": {
    "file": "/matching/species/puma.webp",
    "author": "Carlos",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Puma_-_49044464307.jpg"
  },
  "Рысь": {
    "file": "/matching/species/rys.webp",
    "author": "PaleoMatt",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lynx_collage.png"
  },
  "Серна": {
    "file": "/matching/species/serna.webp",
    "author": "Manfred Werner - Tsui",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:G%C3%A4mse_(Rupicapra_rupicapra)_Zoo_Salzburg_2014_g_(cropped).jpg"
  },
  "Сивуч": {
    "file": "/matching/species/sivuch.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Steller_sea_lion_bull.jpg"
  },
  "Скунс": {
    "file": "/matching/species/skuns.webp",
    "author": "Inao Tomfriedel U.Name.Me Bkentosh",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mephitidae.jpg"
  },
  "Слон": {
    "file": "/matching/species/slon.webp",
    "author": "Yathin S Krishnappa (File:Elephas maximus (Bandipur).jpg) Thomas Breuer (File:Loxodontacyclotis.jpg)) Muhammad Mahdi Karim Facebook The making of this document was supported by Wikimedia CH. (Submit your project!) For all the files concerned, please see the category Supported by Wikimedia CH. العربية ∙ বাংলা ∙ čeština ∙ Deutsch ∙ English ∙ Esperanto ∙ español ∙ français ∙ galego ∙ हिन्दी ∙ magyar ∙ italiano ∙ 日本語 ∙ македонски ∙ Nederlands ∙ português do Brasil ∙ rumantsch ∙ русский ∙ sicilianu ∙ slovenščina ∙ தமிழ் ∙ українська ∙ 中文 ∙ +/− (File:African Bush Elephant.jpg) Derivative work: Sittaco",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephant_Diversity.jpg"
  },
  "Соболь": {
    "file": "/matching/species/sobol.webp",
    "author": "Е.Медведева",
    "license": "Copyrighted free use",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sobol_bur.jpg"
  },
  "Сурок": {
    "file": "/matching/species/surok.webp",
    "author": "No machine-readable author provided. R6MaY89~commonswiki assumed (based on copyright claims).",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DogGroundHog-small.jpg"
  },
  "Суслик": {
    "file": "/matching/species/suslik.webp",
    "author": "Lobkov V.A.",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Spermophilus_suslicus-small.JPG"
  },
  "Тапир": {
    "file": "/matching/species/tapir.webp",
    "author": "Ltshears",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malayan_Tapir_001.jpg"
  },
  "Тигр": {
    "file": "/matching/species/tigr.webp",
    "author": "Appaloosa",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:P.t.altaica_Tomak_Male.jpg"
  },
  "Тюлень": {
    "file": "/matching/species/tyulen.webp",
    "author": "BurakovaLP",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B0%D0%B9%D0%BA%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B5%D1%80%D0%BF%D0%B0.jpg"
  },
  "Хомяк": {
    "file": "/matching/species/homyak.webp",
    "author": "katanski",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hamster.jpg"
  },
  "Хорёк": {
    "file": "/matching/species/horyok.webp",
    "author": "Punetor i Rregullt5",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Weasels_together.jpg"
  },
  "Хорь": {
    "file": "/matching/species/hor.webp",
    "author": "Punetor i Rregullt5",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Weasels_together.jpg"
  },
  "Шакал": {
    "file": "/matching/species/shakal.webp",
    "author": "Raoulduke47",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jackal_Cape_cross_2009.JPG"
  },
  "Ягуар": {
    "file": "/matching/species/yaguar.webp",
    "author": "Silvio Tanaka",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:On%C3%A7a_pintada.jpg"
  },
  "Аист": {
    "file": "/matching/species/aist.webp",
    "author": "Termininja",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ciconia_Diversity.jpg"
  },
  "Альбатрос": {
    "file": "/matching/species/albatros.webp",
    "author": "Michal Klajban based on the mentioned works",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Diomedeidae_collage.jpg"
  },
  "Баклан": {
    "file": "/matching/species/baklan.webp",
    "author": "J.M.Garg",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Indian_Cormorant_(Br.)_I_IMG_8092.jpg"
  },
  "Беркут": {
    "file": "/matching/species/berkut.webp",
    "author": "Jarkko Järvinen",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Maakotka_(Aquila_chrysaetos)_by_Jarkko_J%C3%A4rvinen_(crop).jpg"
  },
  "Буревестник": {
    "file": "/matching/species/burevestnik.webp",
    "author": "JJ Harrison (https://www.jjharrison.com.au/)",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Daption_capense_-_SE_Tasmania_2019.jpg"
  },
  "Вальдшнеп": {
    "file": "/matching/species/valdshnep.webp",
    "author": "Johann Friedrich Naumann",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scolopax_rusticola.jpg"
  },
  "Воробей": {
    "file": "/matching/species/vorobey.webp",
    "author": "S. Shankar",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Petronia_xanthocollis.jpg"
  },
  "Ворон": {
    "file": "/matching/species/voron.webp",
    "author": "Aaron",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Common_Raven_Grand_Canyon_1.jpg"
  },
  "Ворона": {
    "file": "/matching/species/vorona.webp",
    "author": "Zeynel Cebeci",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Corneille_mantel%C3%A9e_-_Hooded_crow_-_Gri_le%C5%9F_kargas%C4%B1_03.jpg"
  },
  "Гагара": {
    "file": "/matching/species/gagara.webp",
    "author": "Len Blumin from Mill Valley, California, United States",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gavia_adamsii.jpg"
  },
  "Гагарка": {
    "file": "/matching/species/gagarka.webp",
    "author": "Francesco Veronesi from Italy",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Razorbill_-_Farne_Is_-_FJ0A1483_(36333754245).jpg"
  },
  "Глухарь": {
    "file": "/matching/species/gluhar.webp",
    "author": "sighmanb",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Capercaillie_(8751340764).jpg"
  },
  "Голубь": {
    "file": "/matching/species/golub.webp",
    "author": "jim.gifford",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ColumbaOenas.jpg"
  },
  "Горлица": {
    "file": "/matching/species/gorlitsa.webp",
    "author": "Horia Varlan",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Streptopelia_decaocto_-balcony_-two-8.jpg"
  },
  "Грач": {
    "file": "/matching/species/grach.webp",
    "author": "Mike Prince from Bangalore, India",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rook_(43893155894).jpg"
  },
  "Дрозд": {
    "file": "/matching/species/drozd.webp",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Redwing_Turdus_iliacus.jpg"
  },
  "Дятел": {
    "file": "/matching/species/dyatel.webp",
    "author": "Rhododendrites",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yellow-bellied_sapsucker_in_CP_(40422).jpg"
  },
  "Журавль": {
    "file": "/matching/species/zhuravl.webp",
    "author": "Fotograf: JeLuF",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jungfernkranich.jpg"
  },
  "Зарянка": {
    "file": "/matching/species/zaryanka.webp",
    "author": "Francis C. Franklin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Erithacus_rubecula_with_cocked_head.jpg"
  },
  "Зимородок": {
    "file": "/matching/species/zimorodok.webp",
    "author": "Artemy Voikhansky",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alcedo_Atthis.jpg"
  },
  "Зуёк": {
    "file": "/matching/species/zuyok.webp",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Charadrius_hiaticula_tundrae_Varanger.jpg"
  },
  "Иволга": {
    "file": "/matching/species/ivolga.webp",
    "author": "Michel Idre from Plaisance du Touch, France",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Loriot_d%27Europe_by_Michel_Idre.jpg"
  },
  "Казарка": {
    "file": "/matching/species/kazarka.webp",
    "author": "Linnea Samila",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Branta_leucopsis.jpg"
  },
  "Кайра": {
    "file": "/matching/species/kayra.webp",
    "author": "US gov",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ThickbilledMurre23.jpg"
  },
  "Камышёвка": {
    "file": "/matching/species/kamyshyovka.webp",
    "author": "Brett Donald",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Australianreedwarbler.jpg"
  },
  "Кеклик": {
    "file": "/matching/species/keklik.webp",
    "author": "Mdf",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alectoris-chukar-001.jpg"
  },
  "Кобчик": {
    "file": "/matching/species/kobchik.webp",
    "author": "Martin Mecnarowski (http://www.photomecan.eu/)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Falco_vespertinus_3_(Martin_Mecnarowski).jpg"
  },
  "Козодой": {
    "file": "/matching/species/kozodoy.webp",
    "author": "Jenny Th",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Caprimulgus_europaeus_1200x855.jpg"
  },
  "Колибри": {
    "file": "/matching/species/kolibri.webp",
    "author": "Ernst Haeckel",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Haeckel_Trochilidae.jpg"
  },
  "Коноплянка": {
    "file": "/matching/species/konoplyanka.webp",
    "author": "Pierre Dalous",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Linaria_cannabina_-_Linotte_m%C3%A9lodieuse.jpg"
  },
  "Коршун": {
    "file": "/matching/species/korshun.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Milvus_migrans_2005-new.jpg"
  },
  "Кречет": {
    "file": "/matching/species/krechet.webp",
    "author": "Falco_rusticolus_white.jpg: Ólafur Larsen derivative work: Bogbumper (talk)",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Falco_rusticolus_white_cropped.jpg"
  },
  "Крохаль": {
    "file": "/matching/species/krohal.webp",
    "author": "Alan D. Wilson",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mergus_serrator.jpg"
  },
  "Кукушка": {
    "file": "/matching/species/kukushka.webp",
    "author": "Wilson44691",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Roadrunner_DeathValley.jpg"
  },
  "Куропатка": {
    "file": "/matching/species/kuropatka.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Perdix_perdix_(Marek_Szczepanek).jpg"
  },
  "Лебедь": {
    "file": "/matching/species/lebed.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mute.swan.touchdown.arp.jpg"
  },
  "Лунь": {
    "file": "/matching/species/lun.webp",
    "author": "Paco Gómez from Castellón, Spain",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Circus_aeruginosus_Valencia_3.jpeg"
  },
  "Малиновка": {
    "file": "/matching/species/malinovka.webp",
    "author": "Francis C. Franklin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Erithacus_rubecula_with_cocked_head.jpg"
  },
  "Мартын": {
    "file": "/matching/species/martyn.webp",
    "author": "Marcel Burkhard (User:Cele4)",
    "license": "CC BY-SA 2.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lachmoewe2cele4.jpg"
  },
  "Мухоловка": {
    "file": "/matching/species/muholovka.webp",
    "author": "Tokumi Ohsaka",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wiki-c-ooruri.jpg"
  },
  "Неясыть": {
    "file": "/matching/species/neyasyt.webp",
    "author": "K.-M. Hansche",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tawny_wiki.jpg"
  },
  "Нырок": {
    "file": "/matching/species/nyrok.webp",
    "author": "Arpingstone",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red-crested.pochard.slimbridge.arp.jpg"
  },
  "Овсянка": {
    "file": "/matching/species/ovsyanka.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gulspurv.jpg"
  },
  "Орёл": {
    "file": "/matching/species/oryol.webp",
    "author": "J. Glover (AUTiger). Please attribute to J. Glover - Atlanta, Georgia in usage outside of Wikimedia Foundation Projects.",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:GoldenEagle-Nova.jpg"
  },
  "Орлан": {
    "file": "/matching/species/orlan.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Riesenseeadler.jpg"
  },
  "Пеночка": {
    "file": "/matching/species/penochka.webp",
    "author": "J.M.Garg",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Greenish_Warbler_I_IMG_0570.jpg"
  },
  "Перепел": {
    "file": "/matching/species/perepel.webp",
    "author": "Luis Miguel Bugallo Sánchez (Lmbuga Commons)(Lmbuga Galipedia) Publicada por/Publish by: Luis Miguel Bugallo Sánchez",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coturnix_coturnix_(Lmbuga).jpg"
  },
  "Петух": {
    "file": "/matching/species/petuh.webp",
    "author": "fir0002 flagstaffotos [at] gmail.com Canon 20D + Tamron 28-75mm f/2.8",
    "license": "GFDL 1.2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rooster02.jpg"
  },
  "Пигалица": {
    "file": "/matching/species/pigalitsa.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kiebitz_050424ausschnitt.jpg"
  },
  "Погоныш": {
    "file": "/matching/species/pogonysh.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Porzana_porzana_3_(Marek_Szczepanek).jpg"
  },
  "Поползень": {
    "file": "/matching/species/popolzen.webp",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eurasian_Nuthatch.jpg"
  },
  "Рябчик": {
    "file": "/matching/species/ryabchik.webp",
    "author": "Wilfried Berns",
    "license": "CC BY-SA 2.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Haselhuhn-01.jpg"
  },
  "Свиристель": {
    "file": "/matching/species/sviristel.webp",
    "author": "Martin Mecnarowski (http://www.photomecan.eu/)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bombycilla_garrulus_1_(Martin_Mecnarowski).jpg"
  },
  "Синица": {
    "file": "/matching/species/sinitsa.webp",
    "author": "Francis Franklin",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parus_major_poised.jpg"
  },
  "Сипуха": {
    "file": "/matching/species/sipuha.webp",
    "author": "Steven Ward",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Barn_Owl,_Lancashire.jpg"
  },
  "Скворец": {
    "file": "/matching/species/skvorets.webp",
    "author": "Anbucco at German Wikipedia (Original text: Andi Buchner)",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Star_Sturnus_vulgaris.jpg"
  },
  "Славка": {
    "file": "/matching/species/slavka.webp",
    "author": "Neil Phillips",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garden_Warbler.jpg"
  },
  "Сова": {
    "file": "/matching/species/sova.webp",
    "author": "This images belongs to his respective owners.",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Portrait_of_owls.jpg"
  },
  "Сокол": {
    "file": "/matching/species/sokol.webp",
    "author": "Thomas Schoch",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Greater_Kestrel_Namibia.jpg"
  },
  "Сорока": {
    "file": "/matching/species/soroka.webp",
    "author": "Alexis Lours",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eurasian_magpie_2022_05_03.jpg"
  },
  "Стриж": {
    "file": "/matching/species/strizh.webp",
    "author": "pau.artigas",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Falciot_3.jpg"
  },
  "Тетерев": {
    "file": "/matching/species/teterev.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_Grouse.jpg"
  },
  "Трясогузка": {
    "file": "/matching/species/tryasoguzka.webp",
    "author": "Artur Mikołajewski",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Motacilla_alba_alba_cropped.JPG"
  },
  "Удод": {
    "file": "/matching/species/udod.webp",
    "author": "J.M.Garg",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Common_Hoopoe_(Upapa_epops)_preening_at_Kolkata_I2_IMG_6985.jpg"
  },
  "Утка": {
    "file": "/matching/species/utka.webp",
    "author": "Alan D. Wilson, www.naturespicsonline.com",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Male_mallard_flight_-_natures_pics.jpg"
  },
  "Филин": {
    "file": "/matching/species/filin.webp",
    "author": "Kamil. Corrections: Piotr_J",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bubo_bubo_winter_1.jpg"
  },
  "Чайка": {
    "file": "/matching/species/chayka.webp",
    "author": "Marcel Burkhard (User:Cele4)",
    "license": "CC BY-SA 2.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lachmoewe2cele4.jpg"
  },
  "Чеглок": {
    "file": "/matching/species/cheglok.webp",
    "author": "Lilly M",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Falco_subbuteo_from_Kadzidlowo.jpg"
  },
  "Чечевица": {
    "file": "/matching/species/chechevitsa.webp",
    "author": "Victor M. Vicente Selvas",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vicia_culinaris_-_Flors_llenties1.jpg"
  },
  "Чечётка": {
    "file": "/matching/species/chechyotka.webp",
    "author": "Jyrki Salmi from Finland",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acanthis_flammea,_Kotka,_Finland_3.jpg"
  },
  "Чибис": {
    "file": "/matching/species/chibis.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kiebitz_050424ausschnitt.jpg"
  },
  "Широконоска": {
    "file": "/matching/species/shirokonoska.webp",
    "author": "Andreas Trepte",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Northern_Shoveler-Anas_clypeata.jpg"
  },
  "Щегол": {
    "file": "/matching/species/schegol.webp",
    "author": "ArminM",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:De_Stieglitz_lat_Carduelis_carduelis.jpg"
  },
  "Щурка": {
    "file": "/matching/species/schurka.webp",
    "author": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:African_bee-eaters_composite.jpg"
  },
  "Акула": {
    "file": "/matching/species/akula.webp",
    "author": "LittleJerry",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TDpGUipa.jpg"
  },
  "Белуга": {
    "file": "/matching/species/beluga.webp",
    "author": "Максим Яковлєв",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%91%D1%96%D0%BB%D1%83%D0%B3%D0%B0_(Huso_huso).jpg"
  },
  "Бычок": {
    "file": "/matching/species/bychok.webp",
    "author": "Daiju Azuma",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stonogobiops_nematodes.jpg"
  },
  "Горбуша": {
    "file": "/matching/species/gorbusha.webp",
    "author": "Timothy Knepp",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pink_salmon_FWS.jpg"
  },
  "Дельфин": {
    "file": "/matching/species/delfin.webp",
    "author": "Arnaud 25",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parc_Asterix_20.jpg"
  },
  "Ёрш": {
    "file": "/matching/species/yorsh.webp",
    "author": "Harka, Akos",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gymnocephalus_cernuus_Hungary.jpg"
  },
  "Зубатка": {
    "file": "/matching/species/zubatka.webp",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anarhichas-lupus-Atlanterhavsparken.jpg"
  },
  "Камбала": {
    "file": "/matching/species/kambala.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pleuronectes_platessa.jpg"
  },
  "Карась": {
    "file": "/matching/species/karas.webp",
    "author": "George Chernilevsky",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carassius_gibelio_2008_G1.jpg"
  },
  "Карп": {
    "file": "/matching/species/karp.webp",
    "author": "Роман АлексеевичЕ",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:%D0%9A%D0%B0%D1%80%D0%BF.jpg"
  },
  "Кета": {
    "file": "/matching/species/keta.webp",
    "author": "NOAA",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oncorhynchus_keta.jpeg"
  },
  "Кефаль": {
    "file": "/matching/species/kefal.webp",
    "author": "Remove \"cropped\" from file name and see original file",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mugil_cephalus_Minorca_cropped.jpg"
  },
  "Краб": {
    "file": "/matching/species/krab.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liocarcinus_vernalis.jpg"
  },
  "Креветка": {
    "file": "/matching/species/krevetka.webp",
    "author": "© 2004 by Tomasz Sienicki [user: tsca, mail: tomasz.sienicki at gmail.com]",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Woda-6_ubt.jpeg"
  },
  "Кутум": {
    "file": "/matching/species/kutum.webp",
    "author": "mrjahan",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kutum.gif"
  },
  "Лещ": {
    "file": "/matching/species/lesch.webp",
    "author": "Piet Spaans",
    "license": "CC BY 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AbramisBramaCarpBream.JPG"
  },
  "Линь": {
    "file": "/matching/species/lin.webp",
    "author": "Viridiflavus",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:FemaleTench1.JPG"
  },
  "Лосось": {
    "file": "/matching/species/losos.webp",
    "author": "Hans-Petter Fjeld",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_salar-Atlantic_Salmon-Atlanterhavsparken_Norway_(cropped).JPG"
  },
  "Макрель": {
    "file": "/matching/species/makrel.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sccav_u0.gif"
  },
  "Мальма": {
    "file": "/matching/species/malma.webp",
    "author": "Bering Land Bridge National Preserve",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dolly-Varden-_Morgan_Bond,_U_of_Washington_edit_(15651417154).jpg"
  },
  "Минтай": {
    "file": "/matching/species/mintay.webp",
    "author": "National Oceanic and Atmospheric Administration",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Walleye_pollock.jpg"
  },
  "Мойва": {
    "file": "/matching/species/moyva.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mallotus_villosus.gif"
  },
  "Морж": {
    "file": "/matching/species/morzh.webp",
    "author": "Nixette",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Walrus_in_the_Russian_Arctic_National_Park,_Novaya_Zemlya_2015-2.jpg"
  },
  "Мурена": {
    "file": "/matching/species/murena.webp",
    "author": "LASZLO ILYES from Cleveland, Ohio, USA",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Muraena_lentiginosa.jpg"
  },
  "Навага": {
    "file": "/matching/species/navaga.webp",
    "author": "Totti",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eleginus_gracilis_Asahiyama_Zoo2.jpg"
  },
  "Нельма": {
    "file": "/matching/species/nelma.webp",
    "author": "Fridtjof Nansen",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:P131a_Alexei,_the_cook,_with_a_nyelma_(Stenodus_nelma).jpg"
  },
  "Нерка": {
    "file": "/matching/species/nerka.webp",
    "author": "David Menke",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_2.jpg"
  },
  "Окунь": {
    "file": "/matching/species/okun.webp",
    "author": "GeSHaFish",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Perca_fluviatilis-female_Siverskiy_Donets_River_Ukraine.jpg"
  },
  "Осётр": {
    "file": "/matching/species/osyotr.webp",
    "author": "Daniel Döhne",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Waxdick_(Acipenser_gueldenstaedtii_)_-_crop.jpg"
  },
  "Палтус": {
    "file": "/matching/species/paltus.webp",
    "author": "Matthieu Godbout",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hippoglossus-hippoglossus-idlm2005.jpg"
  },
  "Пескарь": {
    "file": "/matching/species/peskar.webp",
    "author": "Viridiflavus at Dutch Wikipedia (Original text: Piet Spaans)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Riviergrondel.jpg"
  },
  "Плотва": {
    "file": "/matching/species/plotva.webp",
    "author": "Karelj",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rutilus_rutilus_Prague_Vltava_3.jpg"
  },
  "Пузанок": {
    "file": "/matching/species/puzanok.webp",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alosa_fallax.jpg"
  },
  "Рак": {
    "file": "/matching/species/rak.webp",
    "author": "File:Sally Lightfoot crab (4202519454).jpg: Magnus Manske (uploader), Original by Peter Wilton [1] File:Christmas Island (5775073180).jpg: [2] by DIAC Images File:Lysmata amboinensis in Tropicarium-Oceanarium Budapest.JPG: Хомелка File:RNK jastog.jpg: Ranko",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Decapoda_montage.jpg"
  },
  "Рыбец": {
    "file": "/matching/species/rybets.webp",
    "author": "No machine-readable author provided. Tokic assumed (based on copyright claims).",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vimba_vimba.jpg"
  },
  "Сайда": {
    "file": "/matching/species/sayda.webp",
    "author": "Tino Strauss",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pollachius_virens_01.jpg"
  },
  "Сайра": {
    "file": "/matching/species/sayra.webp",
    "author": "tsuchiya.yoshihiro",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sanma_for_sashimi_by_tsuchiya.yoshihiro.jpg"
  },
  "Сардина": {
    "file": "/matching/species/sardina.webp",
    "author": "Daniel Ventura",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sardin_from_sardegna_1.jpg"
  },
  "Сёмга": {
    "file": "/matching/species/syomga.webp",
    "author": "Hans-Petter Fjeld",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_salar-Atlantic_Salmon-Atlanterhavsparken_Norway_(cropped).JPG"
  },
  "Сиг": {
    "file": "/matching/species/sig.webp",
    "author": "see Iduns kokbok",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sik,_Iduns_kokbok.jpg"
  },
  "Скат": {
    "file": "/matching/species/skat.webp",
    "author": "BEDO (Thailand)",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Taeniura_meyeni.jpg"
  },
  "Ставрида": {
    "file": "/matching/species/stavrida.webp",
    "author": "Вадим де Голь",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Stavrida.jpg"
  },
  "Стерлядь": {
    "file": "/matching/species/sterlyad.webp",
    "author": "Karelj",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acipenser_ruthenus_Prague_Vltava_1.jpg"
  },
  "Судак": {
    "file": "/matching/species/sudak.webp",
    "author": "Emőke Dénes",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hal_-_Sander_lucioperca_-_1.jpg"
  },
  "Таймень": {
    "file": "/matching/species/taymen.webp",
    "author": "Harald Peki (= User Krampus on de.wikipedia)",
    "license": "Attribution",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hucho_hucho.jpg"
  },
  "Тунец": {
    "file": "/matching/species/tunets.webp",
    "author": "aes256",
    "license": "CC BY 2.1 jp",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pacific_bluefin_tuna.jpg"
  },
  "Угорь": {
    "file": "/matching/species/ugor.webp",
    "author": "GerardM",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anguilla_anguilla.jpg"
  },
  "Уклейка": {
    "file": "/matching/species/ukleyka.webp",
    "author": "Piet Spaans",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AlburnusAlburnus1.JPG"
  },
  "Форель": {
    "file": "/matching/species/forel.webp",
    "author": "Eric Engbretson for U.S. Fish and Wildlife Service",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salmo_trutta.jpg"
  },
  "Хариус": {
    "file": "/matching/species/harius.webp",
    "author": "Zsoldos Márton",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thymallus_thymallus_P%C3%A9nzes_p%C3%A9r.jpg"
  },
  "Чехонь": {
    "file": "/matching/species/chehon.webp",
    "author": "Krüger",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pelecus_cultratus1.jpg"
  },
  "Щука": {
    "file": "/matching/species/schuka.webp",
    "author": "Wikimedia Commons",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hecht.jpg"
  },
  "Язь": {
    "file": "/matching/species/yaz.webp",
    "author": "Viridiflavus",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LeuciscusIdusWindeIde56cm_21-4-2009_16-46-58.JPG"
  },
  "Богомол": {
    "file": "/matching/species/bogomol.webp",
    "author": "Plenumchamber",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peygamber_b%C3%B6ce%C4%9Fi_kesik.JPG"
  },
  "Бражник": {
    "file": "/matching/species/brazhnik.webp",
    "author": "Anaxibia",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Acherontia_lachesis_0202.JPG"
  },
  "Веснянка": {
    "file": "/matching/species/vesnyanka.webp",
    "author": "JJ Harrison (https://www.jjharrison.com.au/)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Eusthenia_sp.jpg"
  },
  "Гусеница": {
    "file": "/matching/species/gusenitsa.webp",
    "author": "Didier Descouens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chenille_de_Grand_porte_queue_(macaon).jpg"
  },
  "Жук": {
    "file": "/matching/species/zhuk.webp",
    "author": "Wikipedia Loves Art participant \"etee_in_Space_Ceetee\"",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:WLA_vanda_Collection_of_Beetles.jpg"
  },
  "Жужелица": {
    "file": "/matching/species/zhuzhelitsa.webp",
    "author": "Udo Schmidt from Deutschland",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Carabus_granulatus_Linn%C3%A9,_1758_(2884924385).jpg"
  },
  "Кузнечик": {
    "file": "/matching/species/kuznechik.webp",
    "author": "Wofl",
    "license": "CC BY-SA 2.0 de",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phaneroptera_falcata.jpg"
  },
  "Медведка": {
    "file": "/matching/species/medvedka.webp",
    "author": "Wikimedia Commons",
    "license": "GFDL 1.2",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mole_cricket02.jpg"
  },
  "Муравей": {
    "file": "/matching/species/muravey.webp",
    "author": "Wikimedia Commons",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fire_ants02.jpg"
  },
  "Оса": {
    "file": "/matching/species/osa.webp",
    "author": "Richard Bartz, Munich aka Makro Freak",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vespula_germanica_Richard_Bartz.jpg"
  },
  "Пчела": {
    "file": "/matching/species/pchela.webp",
    "author": "Jon Sullivan",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bee_Collecting_Pollen_2004-08-14.jpg"
  },
  "Саранча": {
    "file": "/matching/species/sarancha.webp",
    "author": "Compton Tucker, NASA GSFC",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:DesertLocust.jpeg"
  },
  "Светляк": {
    "file": "/matching/species/svetlyak.webp",
    "author": "Nevit Dilmen (talk)",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Firefly_Nevit_02670_cr.jpg"
  },
  "Стрекоза": {
    "file": "/matching/species/strekoza.webp",
    "author": "Quartl",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Anax_imperator_qtl2.jpg"
  },
  "Усач": {
    "file": "/matching/species/usach.webp",
    "author": "Udo Schmidt from Deutschland",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cerambyx_cerdo_Linne,_1758_(3034371477).jpg"
  },
  "Шмель": {
    "file": "/matching/species/shmel.webp",
    "author": "Loyna",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bumblebee_2006.jpg"
  },
  "Мотылёк": {
    "file": "/matching/species/motylyok.webp",
    "author": "Morin",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Babochki_rus_enc.jpg"
  },
  "Клоп": {
    "file": "/matching/species/klop.webp",
    "author": "James K. Lindsey",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Palomena.prasina.jpg"
  },
  "Листоед": {
    "file": "/matching/species/listoed.webp",
    "author": "Francisco Welter-Schultes",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chrysomela-populi-08-fws.jpg"
  },
  "Скарабей": {
    "file": "/matching/species/skarabey.webp",
    "author": "Udo Schmidt from Deutschland",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scarabaeus_sacer_Linn%C3%A9,_1758_(28486691625).png"
  }
}
